// lingue/de.ts — tedesco.

import { WEEKLY_QUOTA } from "../modello";
import type { Testi } from "./it";

const de: Testi = {

  greeting: (h: number) => h < 12 ? "Guten Morgen" : h < 18 ? "Guten Tag" : "Guten Abend",
  fmtTime:  (d: Date) => d.toLocaleTimeString("de-DE", { hour:"2-digit", minute:"2-digit" }),
  fmtDay:   (d: Date) => d.toLocaleDateString("de-DE", { weekday:"long", day:"numeric", month:"long" }),
  days:     ["Mo","Di","Mi","Do","Fr","Sa","So"],
  room:     "Zimmer", camera: "Zimmer",
  welcome:  "Einaudi Plus", enterRoom: "Gib deine Zimmernummer ein, um fortzufahren",
  installTitle: "Einaudi Plus installieren",
  installBody: "Füge sie zum Startbildschirm hinzu: Sie öffnet sich im Vollbild und kann dir Erinnerungen schicken.",
  installIosBody: "Auf dem iPhone: Tippe im Browser auf „Teilen“ und dann auf „Zum Home-Bildschirm“.",
  installIosStep: "Teilen  →  Zum Home-Bildschirm",
  installAndroidBody: "Öffne das Browser-Menü und wähle „Zum Startbildschirm zufügen“ (oder „App installieren“).",
  installAndroidStep: "Menü  →  Zum Startbildschirm",
  installCta: "Installieren", installLater: "Später", installIosDone: "Verstanden",
  addFav: "Favorit hinzufügen", day: "Tag", timeSlot: "Zeitfenster", favAlready: "Schon in den Favoriten",
  chooseWasher: "Waschmaschine wählen", noFreeWashers: "In diesem Zeitfenster ist keine Waschmaschine frei.",
  feedback: "Feedback", feedbackBody: "Vorschläge oder ein Problem gefunden? Schreib uns.",
  feedbackPlaceholder: "Schreib hier deine Nachricht…", feedbackSend: "Senden", feedbackSending: "Wird gesendet…",
  feedbackThanks: "Danke! Feedback gesendet ✓", feedbackError: "Senden fehlgeschlagen, versuch es nochmal.",
  skip:     "Ohne Anmeldung fortfahren",
  machines: "Waschmaschinen",
  washers:  "Waschmaschinen", dryers: "Trockner", washer: "Waschmaschine", dryer: "Trockner",
  free:     "Frei", inUse: "Belegt", oos: "Außer Betrieb", operative: "In Betrieb",
  book:     "Buchen", reminder: "Erinnerung", sendReminder: "Erinnerung senden", sent: "Gesendet ✓",
  bookAnyway:   "Trotzdem buchen",
  oosWarnTitle: "Maschine außer Betrieb",
  oosWarnBody:  "Die Verwaltung hat sie geprüft und als defekt markiert. Du kannst sie trotzdem buchen, aber sie wird wahrscheinlich nicht funktionieren.",
  oosDryerWarn: (m: string) => `Trockner ${m} ist außer Betrieb: Du musst die Wäsche eventuell aufhängen.`,
  oosWasherWarn:(m: string) => `Waschmaschine ${m} ist außer Betrieb: Sie startet möglicherweise nicht.`,
  currentSlot: "Aktuelles Zeitfenster", prevSlot: "Vorheriges Zeitfenster", now: "jetzt", prev: "vorh.",
  yourBookings: "Deine Buchungen",
  inProgressNow: "Läuft gerade",
  noActiveBookings: "Keine aktive Buchung",
  freeTodayLabel: "freie Zeitfenster heute",
  favorites: "Favoriten",
  noFavs: "Tippe im Tab „Täglich“ auf den ★ neben einer Uhrzeit, um sie zu den Favoriten hinzuzufügen.",
  favFree: "Frei", favFull: "Voll", favPast: "Vorbei",
  remainingChip: (n: number) => n >= 0 ? `noch ${n}` : `${-n} zu viel`,
  slotEndsIn: "Endet in",
  remainingMsg: (n: number) => n > 0
    ? `Du kannst diese Woche noch ${n} ${n === 1 ? "Zeitfenster" : "Zeitfenster"} buchen (max. ${WEEKLY_QUOTA} pro Zimmer).`
    : n === 0
    ? `Du hast beide Zeitfenster dieser Woche genutzt (max. ${WEEKLY_QUOTA} pro Zimmer).`
    : `Du hast das Wochenlimit von ${WEEKLY_QUOTA} Zeitfenstern überschritten (${-n} zu viel).`,
  altraLavanderia: "Dieses Zimmer gehört zur anderen Waschküche. Du kannst nur die Maschinen deines Gebäudes buchen.",
  noQuota: "ohne Limit",
  howItWorks: "So funktioniert's",
  autoWash: (_end: string) => `Der zugehörige Trockner wird automatisch für das nächste Zeitfenster reserviert.`,
  daily:    "Täglich", weekly: "Woche", overview: "Übersicht",
  thisWeek: "Aktuelle Woche",
  confirm:  "Bestätigen", cancel: "Abbrechen", modify: "Zimmer ändern", delete: "Buchung löschen",
  forMe:    (r: string) => `Für mich — Zimmer ${r}`,
  forOther: "Für jemand anderen",
  forDirezione: "Für die Verwaltung",
  whoIsIt:  "Für wen ist die Buchung?",
  chooseFree: "Wähle eine freie Waschmaschine",
  occupied: "Belegt",
  autoReserved: (lbl: string, t: string) => `Trockner ${lbl} automatisch reserviert: ${t}`,
  confirmBooking: "Buchung bestätigen",
  slotConfirmed:  "Buchung bestätigt",
  slotUpdated:    "Buchung aktualisiert",
  slotDeleted:    "Buchung gelöscht",
  wantModify:     "Möchtest du diese Buchung ändern?",
  bookedBy:       (r: string) => `Gebucht von Zimmer ${r}`,
  machineMgmt:    "Maschinenverwaltung",
  reportOos:      "Defekt melden",
  restore:        "Zurücksetzen",
  oosDesc:        "Melde eine Maschine, die nicht funktioniert: Ein Administrator prüft sie und setzt sie außer Betrieb.",
  reminderSent:   (r: string) => `Erinnerung gesendet · Zimmer ${r}`,
  oosSet:         (lbl: string) => `${lbl} als außer Betrieb gemeldet`,
  oosCleared:     (lbl: string) => `${lbl} wieder in Betrieb`,
  reportAction:   "Melden",
  alreadyOos:     "Bereits gemeldet",
  reportSent:     (lbl: string) => `Defekt für ${lbl} gemeldet. Ein Administrator prüft das.`,
  washerLabel:    "Waschmaschine",
  dryerLabel:     "Trockner",
  notaDesc:       "Was ist kaputt? Optional, hilft aber zu wissen, wen man rufen muss.",
  notaPlaceholder: "z. B. schleudert nicht, verliert Wasser…",
  booked:         (lbl: string) => `Waschmaschine ${lbl} gebucht!`,
  prevHad:        (r: string) => `Zimmer ${r} hatte dieses Zeitfenster vor dir — ist die Wäsche schon abgeholt?`,
  legendFree:     "Grün — Frei", legendFreeDesc: "Du kannst sie sofort buchen.",
  legendInUse:    (t: string) => `Gelb — Belegt — Läuft gerade, Ende um ${t}.`,
  legendPrev:     "Zimmer — Vorheriges Zeitfenster — Zeigt, wer davor dran war.",
  legendOos:      "Rot — Außer Betrieb — Du kannst sie trotzdem buchen, auf eigenes Risiko.",
  legendAuto:     "Automatischer Trockner — wer eine Waschmaschine bucht, bekommt den passenden Trockner für das nächste Zeitfenster.",
  lgFree: "Frei", lgInUse: "Belegt", lgOos: "Außer Betrieb", lgPrev: "Vorheriges Zeitfenster",
  lgFreeD: "Du kannst sie sofort buchen.",
  lgInUseD: (t: string) => `Läuft gerade, Ende um ${t}.`,
  lgOosD: "Defekt von der Verwaltung bestätigt. Du kannst sie trotzdem buchen, auf eigenes Risiko.",
  lgPrevD: "Das Zimmer, das vor dir dran war.",
  insertRoom:     "Zimmernummer",
  back:           "← Zurück",
  backModify:     "← Ändern",
  changeRoom:     "Zimmer wechseln",
  loading:        "Buchungen werden geladen…",
  retry:          "Nochmal versuchen",
  netError:       "Server nicht erreichbar. Prüfe deine Verbindung.",
  taken:          (r?: string) => r ? `Schon von Zimmer ${r} belegt` : "Schon belegt",
  genericError:   "Fehler, versuch es nochmal.",
  soloDirezione:  "Dieses Zeitfenster gehört der Verwaltung: Nur ein Administrator kann es freigeben.",
  navLavanderia: "Waschküche", navCinema: "Kino", navMusica: "Musik",
  navMacchine: "Maschinen", navSegnalazioni: "Meldungen",
  navRicorrenti: "Wiederkehrend", navManutenzione: "Wartung",
  amministrazione: "Verwaltung",
  mesiBrevi: ["Jan","Feb","Mär","Apr","Mai","Jun","Jul","Aug","Sep","Okt","Nov","Dez"],
  navLingua: "Sprache",
  notaFacoltativa: "Optional: Du kannst auch ohne Text absenden.",
  inviaSegnalazione: "Meldung senden",
  impostazioni: "Einstellungen",
  notificheTurni: "Schicht-Erinnerungen",
  notificheBloccate: "Vom Browser blockiert",
  attive: "An",
  nonAttive: "Aus",
  installaApp: "App installieren",
  accessibilita: "Barrierefreiheit",
  promemoriaTurni: "Schicht-Erinnerungen",
  promemoriaDesc: "Wir melden uns kurz bevor dein Zeitfenster beginnt.",
  notifichePhone: "Handy-Benachrichtigungen",
  nonDisponibili: "Auf diesem Gerät nicht verfügbar",
  bloccateBrowser: "In den Browser-Einstellungen blockiert",
  disattiva: "Ausschalten",
  attiva: "Einschalten",
  telegramDesc: "Praktisch auf dem iPhone, wo Push unzuverlässig ist",
  riapri: "Erneut öffnen",
  collega: "Verknüpfen",
  telegramErrore: "Hat nicht geklappt. Versuch es nochmal.",
  nonSiApre: "Hat sich nicht geöffnet?",
  riprovaTelegram: "Telegram erneut öffnen",
  scriviCodice: "Schick dem Bot diesen Code: ",
  codiceUsaEGetta: "Einmalig gültig, läuft in 24 Stunden ab.",
  navConferenze: "Mehrzweck",
  salaConferenze: "Mehrzweckraum",
  liberaOra: "Jetzt frei",
  occupataOra: "Jetzt belegt",
  liberaDalle: (h: string): string => `Frei ab ${h}`,
  nessunaOccupazione: "Nichts geplant.",
  lavBreve: "WM",
  navAccount: "Konten",
  direzioneNome: "Verwaltung",
  sessioneAttiva: (r: string): string => `${r}-Sitzung aktiv: du buchst als Verwaltung. Zum Abmelden oben auf DIREZIONE tippen.`,
  telegramAperto: "Telegram ist offen: tippe im Bot auf START, um dich zu verbinden.",
  usaTastiera: "Du kannst auch über die Tastatur eingeben und Enter drücken.",
  autoReservedLabel: "inbegriffen",
  giornoDopo: "(am Folgetag)",
};

export default de;
