// lingue/en.ts — inglese.

import { WEEKLY_QUOTA } from "../modello";
import type { Testi } from "./it";

const en: Testi = {

  greeting: (h: number) => h < 12 ? "Good morning" : h < 17 ? "Good afternoon" : "Good evening",
  fmtTime:  (d: Date) => d.toLocaleTimeString("en-GB", { hour:"2-digit", minute:"2-digit" }),
  fmtDay:   (d: Date) => d.toLocaleDateString("en-GB", { weekday:"long", day:"numeric", month:"long" }),
  days:     ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
  room:     "Room", camera: "room",
  welcome:  "Einaudi Plus", enterRoom: "Enter your room number to continue",
  installTitle: "Install Einaudi Plus",
  installBody: "Add it to your Home Screen: it opens like a full-screen app and can send you shift reminders.",
  installIosBody: "To install on iPhone: tap the browser Share button, then choose “Add to Home Screen”.",
  installIosStep: "Share  →  Add to Home Screen",
  installAndroidBody: "Open the browser menu and choose “Add page to → Home screen” (or “Install app”).",
  installAndroidStep: "Menu  →  Add to Home screen",
  installCta: "Install", installLater: "Later", installIosDone: "Got it",
  addFav: "Add favourite", day: "Day", timeSlot: "Time slot", favAlready: "Already a favourite",
  chooseWasher: "Choose a washer", noFreeWashers: "No free washer in this slot.",
  feedback: "Feedback", feedbackBody: "Got suggestions or found a problem? Let us know.",
  feedbackPlaceholder: "Type your message here…", feedbackSend: "Send", feedbackSending: "Sending feedback…",
  feedbackThanks: "Thanks! Feedback sent ✓", feedbackError: "Couldn't send, try again.",
  skip:     "Continue without logging in",
  machines: "Machines",
  washers:  "Washers", dryers: "Dryers", washer: "Washer", dryer: "Dryer",
  free:     "Free", inUse: "In use", oos: "Out of service", operative: "Operational",
  book:     "Book", reminder: "Remind", sendReminder: "Send reminder", sent: "Sent ✓",
  bookAnyway:   "Book anyway",
  oosWarnTitle: "Machine out of service",
  oosWarnBody:  "An admin has checked it and marked it broken. You can still book it, but it probably won't work.",
  oosDryerWarn: (m: string) => `Dryer ${m} is out of service: you may have to hang your laundry.`,
  oosWasherWarn:(m: string) => `Washer ${m} is out of service: it may not start.`,
  currentSlot: "Current slot", prevSlot: "Previous slot", now: "now", prev: "prev.",
  yourBookings: "Your bookings",
  inProgressNow: "In progress now",
  noActiveBookings: "No active bookings",
  freeTodayLabel: "free slots today",
  favorites: "Favourites",
  noFavs: "Tap the ★ next to a time in the Daily tab to add it to favourites.",
  favFree: "Free", favFull: "Full", favPast: "Past",
  remainingChip: (n: number) => n >= 0 ? `${n} left` : `${-n} extra`,
  slotEndsIn: "Ends in",
  remainingMsg: (n: number) => n > 0
    ? `You can book ${n} more ${n === 1 ? "slot" : "slots"} this week (max ${WEEKLY_QUOTA} per room).`
    : n === 0
    ? `You've used both your slots this week (max ${WEEKLY_QUOTA} per room).`
    : `You're over the weekly limit of ${WEEKLY_QUOTA} slots (${-n} extra).`,
  altraLavanderia: "That room belongs to the other laundry. You can only book machines in your own building.",
  noQuota: "no limit",
  howItWorks: "How it works",
  autoWash: (_end: string) => `Corresponding dryer auto-reserved for the next slot.`,
  daily:    "Daily", weekly: "Week", overview: "Overview",
  thisWeek: "Current week",
  confirm:  "Confirm", cancel:  "Cancel", modify: "Edit room", delete: "Delete booking",
  forMe:    (r: string) => `For me — Room ${r}`,
  forOther: "For someone else",
  forDirezione: "For the front desk",
  whoIsIt:  "Who is this booking for?",
  chooseFree: "Choose a free washer",
  occupied: "Taken",
  autoReserved: (lbl: string, t: string) => `Dryer ${lbl} auto-reserved: ${t}`,
  confirmBooking: "Confirm booking",
  slotConfirmed:  "Booking confirmed",
  slotUpdated:    "Booking updated",
  slotDeleted:    "Booking deleted",
  wantModify:     "Do you want to edit this booking?",
  bookedBy:       (r: string) => `Booked by room ${r}`,
  machineMgmt:    "Machine management",
  reportOos:      "Report a fault",
  restore:        "Restore",
  oosDesc:        "Report a machine that isn't working: an admin will check and mark it out of order.",
  reportAction:   "Report",
  alreadyOos:     "Already reported",
  reportSent:     (lbl: string) => `Fault reported for ${lbl}. An admin will check it.`,
  washerLabel:    "Washer",
  dryerLabel:     "Dryer",
  notaDesc:       "What is wrong? Optional, but it helps decide who to call.",
  notaPlaceholder: "e.g. will not spin, leaking…",
  reminderSent:   (r: string) => `Reminder sent · Room ${r}`,
  oosSet:         (lbl: string) => `${lbl} marked out of order`,
  oosCleared:     (lbl: string) => `${lbl} restored`,
  booked:         (lbl: string) => `Washer ${lbl} booked!`,
  prevHad:        (r: string) => `Room ${r} had this slot before you — have they collected their laundry?`,
  legendFree:     "Green — Free", legendFreeDesc: "Book it now.",
  legendInUse:    (t: string) => `Yellow — In use — Slot ends at ${t}.`,
  legendPrev:     "Room — Previous slot — Shows who had the slot before you.",
  legendOos:      "Red — Out of service — You can still book it, at your own risk.",
  legendAuto:     "Auto-dryer — booking a washer automatically reserves the matching dryer for the next slot.",
  lgFree: "Free", lgInUse: "In use", lgOos: "Out of service", lgPrev: "Previous slot",
  lgFreeD: "Book it now.",
  lgInUseD: (t: string) => `In progress, ends at ${t}.`,
  lgOosD: "Fault confirmed by an admin. You can still book it, at your own risk.",
  lgPrevD: "The room that had the slot before you.",
  insertRoom:     "Room number",
  back:           "← Back",
  backModify:     "← Edit",
  changeRoom:     "Change room",
  loading:        "Loading bookings…",
  retry:          "Retry",
  netError:       "Couldn't reach the server. Check your connection.",
  taken:          (r?: string) => r ? `Already taken by room ${r}` : "Already taken",
  genericError:   "Error, try again.",
  soloDirezione:  "This slot belongs to the front desk: only an administrator can free it.",
  navLavanderia: "Laundry", navCinema: "Cinema", navMusica: "Music",
  navMacchine: "Machines", navSegnalazioni: "Reports",
  navRicorrenti: "Recurring", navManutenzione: "Maintenance",
  amministrazione: "Administration",
  mesiBrevi: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
  navLingua: "Language",
  notaFacoltativa: "Optional: you can send it without writing anything.",
  inviaSegnalazione: "Send the report",
  impostazioni: "Settings",
  notificheTurni: "Shift reminders",
  notificheBloccate: "Blocked by the browser",
  attive: "On",
  nonAttive: "Off",
  installaApp: "Install the app",
  accessibilita: "Accessibility",
  promemoriaTurni: "Shift reminders",
  promemoriaDesc: "We'll ping you shortly before your shift starts.",
  notifichePhone: "Phone notifications",
  nonDisponibili: "Not available on this device",
  bloccateBrowser: "Blocked in browser settings",
  disattiva: "Turn off",
  attiva: "Turn on",
  telegramDesc: "Handy on iPhone, where push is unreliable",
  riapri: "Reopen",
  collega: "Link",
  telegramErrore: "Didn't work. Try again.",
  nonSiApre: "Didn't open?",
  riprovaTelegram: "Try opening Telegram again",
  scriviCodice: "Message the bot this code: ",
  codiceUsaEGetta: "Single use, expires in 24 hours.",
  navConferenze: "Conference",
  salaConferenze: "Conference room",
  liberaOra: "Free right now",
  occupataOra: "In use right now",
  liberaDalle: (h: string): string => `Free from ${h}`,
  prossimeOccupazioni: "Upcoming bookings",
  nessunaOccupazione: "Nothing scheduled.",
  oggi: "today",
  guardaTreMesi: "See the next three months",
  guardaAnno: "See the whole year",
  lavBreve: "Wash.",
  navProgrammazione: "Scheduling",
  navAccount: "Accounts",
};

export default en;
