// lingue/en.ts — inglese.

import { WEEKLY_QUOTA } from "../modello";
import type { Testi } from "./it";

const en: Testi = {

  greeting: (h: number) => h < 12 ? "Good morning" : h < 17 ? "Good afternoon" : "Good evening",
  fmtTime:  (d: Date) => d.toLocaleTimeString("en-GB", { hour:"2-digit", minute:"2-digit" }),
  fmtDay:   (d: Date) => d.toLocaleDateString("en-GB", { weekday:"long", day:"numeric", month:"long" }),
  days:     ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
  room:     "Room", camera: "room",
  welcome:  "Einaudi Plus", enterRoom: "Enter your room number to continue",
  installTitle: "Install Einaudi Plus",
  installBody: "Add it to your Home Screen: it opens like a full-screen app and can send you shift reminders.",
  installIosBody: "To install on iPhone: tap the browser Share button, then choose “Add to Home Screen”.",
  installIosStep: "Share  →  Add to Home Screen",
  installAndroidBody: "Open the browser menu and choose “Add page to → Home screen” (or “Install app”).",
  installAndroidStep: "Menu  →  Add to Home screen",
  installCta: "Install", installLater: "Later", installIosDone: "Got it",
  favsIntro: "The slots you want back every week.",
  addFav: "Add favourite",
  removeFav: "Remove favourite", day: "Day", timeSlot: "Time slot", favAlready: "Already a favourite",
  chooseWasher: "Choose a washer", noFreeWashers: "No free washer in this slot.",
  feedback: "Feedback", feedbackBody: "Got suggestions or found a problem? Let us know.",
  feedbackPlaceholder: "Type your message here…", feedbackSend: "Send", feedbackSending: "Sending feedback…",
  feedbackThanks: "Thanks! Feedback sent ✓", feedbackError: "Couldn't send, try again.",
  skip:     "Continue without logging in",
  machines: "Machines",
  washers:  "Washers", dryers: "Dryers", washer: "Washer", dryer: "Dryer",
  free:     "Free", inUse: "In use", oos: "Out of service", operative: "Operational",
  book:     "Book", reminder: "Remind", sendReminder: "Send reminder", sent: "Sent ✓",
  bookAnyway:   "Book anyway",
  oosWarnTitle: "Machine out of service",
  oosWarnBody:  "An admin has checked it and marked it broken. You can still book it, but it probably won't work.",
  oosDryerWarn: (m: string) => `Dryer ${m} is out of service: you may have to hang your laundry.`,
  oosWasherWarn:(m: string) => `Washer ${m} is out of service: it may not start.`,
  currentSlot: "Current slot", prevSlot: "Previous slot", now: "now", prev: "prev.",
  yourBookings: "Your bookings",
  bookToday:     "Book for today",
  bookTodayHint: "Pick a free slot from today",
  bookOtherDay:     "Book another day",
  bookOtherDayHint: "See the whole week and choose",
  backToDashboard:  "Back to dashboard",
  navStrutture: "Menu",
  bookTitle: "Book",
  feedbackApp: "Feedback on the app",
  machinesInfo: "Who has the machines this slot, and who had them before.",
  inProgressNow: "In progress now",
  noActiveBookings: "No active bookings",
  freeTodayLabel: "free slots today",
  favorites: "Favourites",
  noFavs: "Tap the ★ next to a time in the Daily tab to add it to favourites.",
  bookSlot: "Book a slot",
  bookAnother: "Book another slot",
  favAvailable: "Your favourite slot is free",
  favFree: "Free", favFull: "Full", favPast: "Past",
  remainingChip: (n: number) => n >= 0 ? `${n} left` : `${-n} extra`,
  slotFrom: (ora: string): string => `Slot from ${ora}`,
  slotEndsIn: "Ends in",
  remainingMsg: (n: number) => n > 0
    ? `You can book ${n} more ${n === 1 ? "slot" : "slots"} this week (max ${WEEKLY_QUOTA} per room).`
    : n === 0
    ? `You've used both your slots this week (max ${WEEKLY_QUOTA} per room).`
    : `You're over the weekly limit of ${WEEKLY_QUOTA} slots (${-n} extra).`,
  altraLavanderia: "That room belongs to the other laundry. You can only book machines in your own building.",
  noQuota: "no limit",
  howItWorks: "How it works",
  autoWash: (_end: string) => `Corresponding dryer auto-reserved for the next slot.`,
  daily:    "Daily", weekly: "Week", overview: "Overview",
  thisWeek: "Current week",
  confirm:  "Confirm", cancel:  "Cancel", modify: "Edit room", delete: "Delete booking",
  forMe:    (r: string) => `For me — Room ${r}`,
  forOther: "For someone else",
  forDirezione: "For the front desk",
  whoIsIt:  "Who is this booking for?",
  chooseFree: "Choose a free washer",
  occupied: "Taken",
  autoReserved: (lbl: string, t: string) => `Dryer ${lbl} auto-reserved: ${t}`,
  confirmBooking: "Confirm booking",
  slotConfirmed:  "Booking confirmed",
  slotUpdated:    "Booking updated",
  slotDeleted:    "Booking deleted",
  wantModify:     "Do you want to edit this booking?",
  bookedBy:       (r: string) => `Booked by room ${r}`,
  machineMgmt:    "Machine management",
  reportOos:      "Report a fault",
  restore:        "Restore",
  oosDesc:        "Report a machine that isn't working: an admin will check and mark it out of order.",
  reportAction:   "Report",
  alreadyOos:     "Already reported",
  reportSent:     (lbl: string) => `Fault reported for ${lbl}. An admin will check it.`,
  washerLabel:    "Washer",
  dryerLabel:     "Dryer",
  notaDesc:       "What is wrong? Optional, but it helps decide who to call.",
  notaPlaceholder: "e.g. will not spin, leaking…",
  reminderSent:   (r: string) => `Reminder sent · Room ${r}`,
  oosSet:         (lbl: string) => `${lbl} marked out of order`,
  oosCleared:     (lbl: string) => `${lbl} restored`,
  prevHad:        (r: string) => `Room ${r} had this slot before you — have they collected their laundry?`,
  legendFree:     "Green — Free", legendFreeDesc: "Book it now.",
  legendInUse:    (t: string) => `Yellow — In use — Slot ends at ${t}.`,
  legendPrev:     "Room — Previous slot — Shows who had the slot before you.",
  legendOos:      "Red — Out of service — You can still book it, at your own risk.",
  legendAuto:     "Auto-dryer — booking a washer automatically reserves the matching dryer for the next slot.",
  lgFree: "Free", lgInUse: "In use", lgOos: "Out of service", lgPrev: "Previous slot",
  lgFreeD: "Nobody has taken this slot.",
  lgInUseD: (t: string) => `In progress, ends at ${t}.`,
  lgOosD: "Fault confirmed by an admin. You can still book it, at your own risk.",
  lgPrevD: "The room that had the slot before you.",
  insertRoom:     "Room number",
  back:           "← Back",
  backModify:     "← Edit",
  changeRoom:     "Change room",
  loading:        "Loading bookings…",
  retry:          "Retry",
  netError:       "Couldn't reach the server. Check your connection.",
  taken:          (r?: string) => r ? `Already taken by room ${r}` : "Already taken",
  genericError:   "Error, try again.",
  soloDirezione:  "This slot belongs to the front desk: only an administrator can free it.",
  navLavanderia: "Laundry", navCinema: "Cinema", navMusica: "Music",
  navMacchine: "Machines", navSegnalazioni: "Reports",
  navRicorrenti: "Recurring", navManutenzione: "Maintenance",
  amministrazione: "Administration",
  mesiBrevi: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
  navLingua: "Language",
  notaFacoltativa: "Optional: you can send it without writing anything.",
  inviaSegnalazione: "Send the report",
  impostazioni: "Settings",
  notificheTurni: "Shift reminders",
  notificheBloccate: "Blocked by the browser",
  attive: "On",
  nonAttive: "Off",
  installaApp: "Install the app",
  accessibilita: "Accessibility",
  privacy: "Privacy", privacySub: "How we handle your data",
  privacyDatiTitolo: "What data we collect",
  privacyDatiBody: "The room number you enter to log in; if you turn on reminders, your device's identifier (for push notifications) or your chat identifier (for Telegram); the text of any reports you send. We don't ask for your name or other personal details — but the room number is still data that could be traced back to you by anyone who knows who lives in that room.",
  privacyPercheTitolo: "Why we use it",
  privacyPercheBody: "To let you book laundry and room slots, avoid double bookings and overlaps, and — only if you turn it on — send you a reminder shortly before your slot starts.",
  privacyConservazioneTitolo: "How long we keep it",
  privacyConservazioneBody: "Bookings stay visible for the current week and the previous one, then get deleted automatically. Reports and technical logs are deleted after 180 days. A reminder subscription (push or Telegram) stays active until you turn it off yourself in Settings, or send /stop to the Telegram bot.",
  privacyCondivisioneTitolo: "Who we share data with",
  privacyCondivisioneBody: "The app runs on Vercel and the database on Supabase, which host them on our behalf. If you turn on reminders, your device or account receives messages through your browser's push service (Google, Apple or Mozilla, depending on your device) or through Telegram. We don't sell or share your data for any other purpose.",
  privacyDirittiTitolo: "Your rights",
  privacyDirittiBody: "You can turn off reminders at any time in Settings: this immediately deletes the push or Telegram subscription linked to your device. To access, correct or delete other data about you (e.g. a report you sent), contact whoever manages the app.",
  promemoriaTurni: "Shift reminders",
  promemoriaDesc: "We'll ping you shortly before your shift starts.",
  notifichePhone: "Phone notifications",
  nonDisponibili: "Not available on this device",
  bloccateBrowser: "Blocked in browser settings",
  disattiva: "Turn off",
  attiva: "Turn on",
  nonOra: "Not now",
  telegramDesc: "Handy on iPhone, where push is unreliable",
  riapri: "Reopen",
  collega: "Link",
  telegramErrore: "Didn't work. Try again.",
  nonSiApre: "Didn't open?",
  riprovaTelegram: "Try opening Telegram again",
  scriviCodice: "Message the bot this code: ",
  codiceUsaEGetta: "Single use, expires in 24 hours.",
  navConferenze: "Multipurpose",
  salaConferenze: "Multipurpose Room",
  liberaOra: "Free right now",
  occupataOra: "In use right now",
  liberaDalle: (h: string): string => `Free from ${h}`,
  nessunaOccupazione: "Nothing scheduled.",
  lavBreve: "Wash.",
  navAccount: "Accounts",
  direzioneNome: "Front desk",
  sessioneAttiva: (r: string): string => `${r} session active: you book as Direzione. Tap DIREZIONE at the top to sign out.`,
  telegramAperto: "Telegram is open: tap START in the bot and you're linked.",
  usaTastiera: "You can also type on your keyboard and press Enter.",
  autoReservedLabel: "included",
  giornoDopo: "(the next day)",
};

export default en;
