// lingue/es.ts — spagnolo.

import { WEEKLY_QUOTA } from "../modello";
import type { Testi } from "./it";

const es: Testi = {

  greeting: (h: number) => h < 12 ? "Buenos días" : h < 20 ? "Buenas tardes" : "Buenas noches",
  fmtTime:  (d: Date) => d.toLocaleTimeString("es-ES", { hour:"2-digit", minute:"2-digit" }),
  fmtDay:   (d: Date) => d.toLocaleDateString("es-ES", { weekday:"long", day:"numeric", month:"long" }),
  days:     ["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"],
  room:     "Habitación", camera: "habitación",
  welcome:  "Einaudi Plus", enterRoom: "Escribe el número de tu habitación para entrar",
  installTitle: "Instalar Einaudi Plus",
  installBody: "Añádela a la pantalla de inicio: se abre a pantalla completa y puede enviarte los recordatorios de los turnos.",
  installIosBody: "Para instalarla en iPhone: toca el botón Compartir del navegador y luego «Añadir a inicio».",
  installIosStep: "Compartir  →  Añadir a inicio",
  installAndroidBody: "Abre el menú del navegador y elige «Añadir a pantalla de inicio» (o «Instalar aplicación»).",
  installAndroidStep: "Menú  →  Añadir a pantalla de inicio",
  installCta: "Instalar", installLater: "Más tarde", installIosDone: "Entendido",
  favsIntro: "Los turnos que quieres cada semana.",
  addFav: "Añadir favorito",
  removeFav: "Quitar de favoritos", day: "Día", timeSlot: "Franja horaria", favAlready: "Ya está en favoritos",
  chooseWasher: "Elige la lavadora", noFreeWashers: "No hay ninguna lavadora libre en este turno.",
  feedback: "Comentarios", feedbackBody: "¿Tienes sugerencias o has encontrado un problema? Escríbenos.",
  feedbackPlaceholder: "Escribe aquí tu mensaje…", feedbackSend: "Enviar", feedbackSending: "Enviando…",
  feedbackThanks: "¡Gracias! Mensaje enviado ✓", feedbackError: "No se pudo enviar, inténtalo otra vez.",
  skip:     "Continuar sin identificarse",
  machines: "Lavadoras",
  washers:  "Lavadoras", dryers: "Secadoras", washer: "Lavadora", dryer: "Secadora",
  free:     "Libre", inUse: "En uso", oos: "Fuera de servicio", operative: "En servicio",
  book:     "Reservar", reminder: "Recordatorio", sendReminder: "Enviar recordatorio", sent: "Enviado ✓",
  bookAnyway:   "Reservar igualmente",
  oosWarnTitle: "Máquina fuera de servicio",
  oosWarnBody:  "La administración la ha comprobado y marcado como averiada. Puedes reservarla igualmente, pero es probable que no funcione.",
  oosDryerWarn: (m: string) => `La secadora ${m} está fuera de servicio: puede que tengas que tender la ropa.`,
  oosWasherWarn:(m: string) => `La lavadora ${m} está fuera de servicio: puede que no arranque.`,
  currentSlot: "Turno actual", prevSlot: "Turno anterior", now: "ahora", prev: "ant.",
  yourBookings: "Tus reservas",
  bookToday:     "Reservar para hoy",
  bookTodayHint: "Elige un turno libre de hoy",
  bookOtherDay:     "Reservar otro día",
  bookOtherDayHint: "Mira toda la semana y elige",
  backToDashboard:  "Volver al panel",
  navStrutture: "Menú",
  bookTitle: "Reservar",
  feedbackApp: "Opinión sobre la app",
  machinesInfo: "Quién tiene las máquinas en este turno, y quién las tenía antes.",
  inProgressNow: "En curso",
  noActiveBookings: "Ninguna reserva activa",
  freeTodayLabel: "turnos libres hoy",
  favorites: "Favoritos",
  noFavs: "Toca la ★ junto a un horario en la pestaña Diario para añadirlo a favoritos.",
  bookSlot: "Reservar un turno",
  bookAnother: "Reservar otro turno",
  favAvailable: "Tu turno favorito está libre",
  favFree: "Libre", favFull: "Lleno", favPast: "Pasado",
  remainingChip: (n: number) => n >= 0 ? `${n} restante${n === 1 ? "" : "s"}` : `${-n} de más`,
  slotFrom: (ora: string): string => `Turno de las ${ora}`,
  slotEndsIn: "Termina en",
  remainingMsg: (n: number) => n > 0
    ? `Todavía puedes reservar ${n} turno${n === 1 ? "" : "s"} esta semana (máx. ${WEEKLY_QUOTA} por habitación).`
    : n === 0
    ? `Has usado los dos turnos de esta semana (máx. ${WEEKLY_QUOTA} por habitación).`
    : `Has superado el límite semanal de ${WEEKLY_QUOTA} turnos (${-n} de más).`,
  altraLavanderia: "Esa habitación es de la otra lavandería. Solo puedes reservar las máquinas de tu edificio.",
  noQuota: "sin límite",
  howItWorks: "Cómo funciona",
  autoWash: (_end: string) => `La secadora correspondiente se reserva automáticamente para el turno siguiente.`,
  daily:    "Diario", weekly: "Semana", overview: "Resumen",
  thisWeek: "Semana actual",
  confirm:  "Confirmar", cancel: "Cancelar", modify: "Cambiar habitación", delete: "Eliminar reserva",
  forMe:    (r: string) => `Para mí — Habitación ${r}`,
  forOther: "Para otra persona",
  forDirezione: "Para la Dirección",
  whoIsIt:  "¿Para quién es la reserva?",
  chooseFree: "Elige una lavadora libre",
  occupied: "Ocupada",
  autoReserved: (lbl: string, t: string) => `Secadora ${lbl} reservada automáticamente: ${t}`,
  confirmBooking: "Confirmar reserva",
  slotConfirmed:  "Reserva confirmada",
  slotUpdated:    "Reserva actualizada",
  slotDeleted:    "Reserva eliminada",
  wantModify:     "¿Quieres modificar esta reserva?",
  bookedBy:       (r: string) => `Reservada por la habitación ${r}`,
  machineMgmt:    "Gestión de máquinas",
  reportOos:      "Informar de una avería",
  restore:        "Restablecer",
  oosDesc:        "Informa de una máquina que no funciona: un administrador lo comprueba y la pone fuera de servicio.",
  reminderSent:   (r: string) => `Recordatorio enviado · Habitación ${r}`,
  oosSet:         (lbl: string) => `${lbl} marcada fuera de servicio`,
  oosCleared:     (lbl: string) => `${lbl} restablecida`,
  reportAction:   "Informar",
  alreadyOos:     "Ya informada",
  reportSent:     (lbl: string) => `Avería informada para ${lbl}. Un administrador la comprobará.`,
  washerLabel:    "Lavadora",
  dryerLabel:     "Secadora",
  notaDesc:       "¿Qué le pasa? Es opcional, pero ayuda a saber a quién llamar.",
  notaPlaceholder: "Ej. no centrifuga, pierde agua…",
  prevHad:        (r: string) => `La habitación ${r} tenía este turno antes que tú — ¿ya ha recogido la ropa?`,
  legendFree:     "Verde — Libre", legendFreeDesc: "Puedes reservarla ahora mismo.",
  legendInUse:    (t: string) => `Amarillo — En uso — Turno en curso, termina a las ${t}.`,
  legendPrev:     "Habitación — Turno anterior — Indica quién tenía el turno antes que tú.",
  legendOos:      "Rojo — Fuera de servicio — Puedes reservarla igualmente, bajo tu responsabilidad.",
  legendAuto:     "Secadora automática — al reservar una lavadora, la secadora correspondiente queda reservada para el turno siguiente.",
  lgFree: "Libre", lgInUse: "En uso", lgOos: "Fuera de servicio", lgPrev: "Turno anterior",
  lgFreeD: "Nadie ha cogido este turno.",
  lgInUseD: (t: string) => `Turno en curso, termina a las ${t}.`,
  lgOosD: "Avería confirmada por la administración. Puedes reservarla igualmente, bajo tu responsabilidad.",
  lgPrevD: "La habitación que tenía el turno antes que tú.",
  insertRoom:     "Número de habitación",
  back:           "← Atrás",
  backModify:     "← Modificar",
  changeRoom:     "Cambiar habitación",
  loading:        "Cargando las reservas…",
  retry:          "Reintentar",
  netError:       "No se puede contactar con el servidor. Comprueba tu conexión.",
  taken:          (r?: string) => r ? `Ya ocupada por la habitación ${r}` : "Ya ocupada",
  genericError:   "Error, inténtalo otra vez.",
  soloDirezione:  "Este turno es de la Dirección: solo un administrador puede liberarlo.",
  navLavanderia: "Lavandería", navCinema: "Cine", navMusica: "Música",
  navMacchine: "Máquinas", navSegnalazioni: "Avisos",
  navRicorrenti: "Recurrentes", navManutenzione: "Mantenimiento",
  amministrazione: "Administración",
  mesiBrevi: ["ene","feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic"],
  navLingua: "Idioma",
  notaFacoltativa: "Opcional: puedes enviarlo sin escribir nada.",
  inviaSegnalazione: "Enviar el aviso",
  impostazioni: "Ajustes",
  notificheTurni: "Avisos de turnos",
  notificheBloccate: "Bloqueadas por el navegador",
  attive: "Activados",
  nonAttive: "Desactivados",
  installaApp: "Instalar la aplicación",
  accessibilita: "Accesibilidad",
  promemoriaTurni: "Recordatorios de turnos",
  promemoriaDesc: "Te avisamos poco antes de que empiece tu turno.",
  notifichePhone: "Notificaciones del teléfono",
  nonDisponibili: "No disponibles en este dispositivo",
  bloccateBrowser: "Bloqueadas en los ajustes del navegador",
  disattiva: "Desactivar",
  attiva: "Activar",
  nonOra: "Ahora no",
  telegramDesc: "Útil en iPhone, donde las notificaciones fallan a menudo",
  riapri: "Reabrir",
  collega: "Vincular",
  telegramErrore: "No ha funcionado. Inténtalo otra vez.",
  nonSiApre: "¿No se ha abierto?",
  riprovaTelegram: "Reintentar abrir Telegram",
  scriviCodice: "Envía este código al bot: ",
  codiceUsaEGetta: "De un solo uso, caduca en 24 horas.",
  navConferenze: "Polivalente",
  salaConferenze: "Sala Polivalente",
  liberaOra: "Libre ahora",
  occupataOra: "Ocupada ahora",
  liberaDalle: (h: string): string => `Libre a partir de las ${h}`,
  nessunaOccupazione: "No hay nada programado.",
  lavBreve: "Lav.",
  navAccount: "Cuentas",
  direzioneNome: "Dirección",
  sessioneAttiva: (r: string): string => `Sesión ${r} activa: reservas como Dirección. Para salir, toca DIREZIONE arriba.`,
  telegramAperto: "Telegram está abierto: toca INICIAR en el bot para quedar conectado.",
  usaTastiera: "También puedes escribir con el teclado y pulsar Intro.",
  autoReservedLabel: "incluida",
  giornoDopo: "(del día siguiente)",
};

export default es;
