// lingue/fr.ts — francese.

import { WEEKLY_QUOTA } from "../modello";
import type { Testi } from "./it";

const fr: Testi = {

  greeting: (h: number) => h < 12 ? "Bonjour" : h < 18 ? "Bon après-midi" : "Bonsoir",
  fmtTime:  (d: Date) => d.toLocaleTimeString("fr-FR", { hour:"2-digit", minute:"2-digit" }),
  fmtDay:   (d: Date) => d.toLocaleDateString("fr-FR", { weekday:"long", day:"numeric", month:"long" }),
  days:     ["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"],
  room:     "Chambre", camera: "chambre",
  welcome:  "Einaudi Plus", enterRoom: "Saisis ton numéro de chambre pour continuer",
  installTitle: "Installer Einaudi Plus",
  installBody: "Ajoute-la à l'écran d'accueil : elle s'ouvre en plein écran et peut t'envoyer les rappels de créneaux.",
  installIosBody: "Pour l'installer sur iPhone : touche le bouton Partager du navigateur, puis « Sur l'écran d'accueil ».",
  installIosStep: "Partager  →  Sur l'écran d'accueil",
  installAndroidBody: "Ouvre le menu du navigateur et choisis « Ajouter à l'écran d'accueil » (ou « Installer l'application »).",
  installAndroidStep: "Menu  →  Ajouter à l'écran d'accueil",
  installCta: "Installer", installLater: "Plus tard", installIosDone: "J'ai compris",
  favsIntro: "Les créneaux que tu reprends chaque semaine.",
  addFav: "Ajouter vos préférences",
  removeFav: "Retirer des préférences", day: "Jour", timeSlot: "Créneau horaire", favAlready: "Déjà dans les préférences",
  chooseWasher: "Choisis la machine à laver", noFreeWashers: "Aucune machine à laver libre sur ce créneau.",
  feedback: "Retour", feedbackBody: "Une suggestion ou un problème ? Écris-nous.",
  feedbackPlaceholder: "Écris ton message ici…", feedbackSend: "Envoyer", feedbackSending: "Envoi en cours…",
  feedbackThanks: "Merci ! Message envoyé ✓", feedbackError: "L'envoi a échoué, réessaie.",
  skip:     "Continuer sans s'identifier",
  machines: "Machines à laver",
  washers:  "Machines à laver", dryers: "Sèche-linge", washer: "Machine à laver", dryer: "Sèche-linge",
  free:     "Libre", inUse: "Occupé", oos: "Hors service", operative: "En service",
  book:     "Réserver", reminder: "Rappel", sendReminder: "Envoyer un rappel", sent: "Envoyé ✓",
  bookAnyway:   "Réserver quand même",
  oosWarnTitle: "Machine hors service",
  oosWarnBody:  "L'administration l'a vérifiée et signalée comme en panne. Tu peux quand même la réserver, mais elle ne marchera probablement pas.",
  oosDryerWarn: (m: string) => `Le sèche-linge ${m} est hors service : tu devras peut-être étendre ton linge.`,
  oosWasherWarn:(m: string) => `La machine à laver ${m} est hors service : elle risque de ne pas démarrer.`,
  currentSlot: "Créneau en cours", prevSlot: "Créneau précédent", now: "maint.", prev: "préc.",
  yourBookings: "Tes réservations",
  bookToday:     "Réserver pour aujourd'hui",
  bookTodayHint: "Choisis un créneau libre d'aujourd'hui",
  bookOtherDay:     "Réserver un autre jour",
  bookOtherDayHint: "Vois toute la semaine et choisis",
  backToDashboard:  "Retour à la page d'accueil",
  navStrutture: "Menu",
  bookTitle: "Réserver",
  feedbackApp: "Avis sur l'appli",
  machinesInfo: "Qui utilise les machines sur ce créneau, et qui les a utilisés avant.",
  inProgressNow: "En cours",
  noActiveBookings: "Aucune réservation en cours",
  freeTodayLabel: "créneaux libres aujourd'hui",
  favorites: "Préférences",
  noFavs: "Touchez la ★ à côté d'un horaire dans l'onglet Journalier pour l'ajouter à vos préférences.",
  bookSlot: "Réserver un créneau",
  bookAnother: "Réserver un autre créneau",
  favAvailable: "Ton créneau favori est libre",
  favFree: "Libre", favFull: "Complet", favPast: "Passé",
  remainingChip: (n: number) => n >= 0 ? `${n} restant${n === 1 ? "" : "s"}` : `${-n} en trop`,
  slotFrom: (ora: string): string => `Créneau de ${ora}`,
  slotEndsIn: "Se termine dans",
  remainingMsg: (n: number) => n > 0
    ? `Tu peux encore réserver ${n} créneau${n === 1 ? "" : "x"} cette semaine (max ${WEEKLY_QUOTA} par chambre).`
    : n === 0
    ? `Tu as utilisé tes deux créneaux de la semaine (max ${WEEKLY_QUOTA} par chambre).`
    : `Tu as dépassé la limite de ${WEEKLY_QUOTA} créneaux par semaine (${-n} en trop).`,
  altraLavanderia: "Cette chambre dépend de l'autre buanderie. Tu ne peux réserver que les machines de ton bâtiment.",
  noQuota: "sans limite",
  howItWorks: "Comment ça marche",
  autoWash: (_end: string) => `Le sèche-linge correspondant est réservé automatiquement pour le créneau suivant.`,
  daily:    "Journalier", weekly: "Hebdomadaire", overview: "Vue d'ensemble",
  thisWeek: "Semaine en cours",
  confirm:  "Confirmer", cancel: "Annuler", modify: "Changer de chambre", delete: "Supprimer la réservation",
  forMe:    (r: string) => `Pour moi — Chambre ${r}`,
  forOther: "Pour quelqu'un d'autre",
  forDirezione: "Pour la Direction",
  whoIsIt:  "Pour qui est la réservation ?",
  chooseFree: "Choisis une machine à laver libre",
  occupied: "Occupé",
  autoReserved: (lbl: string, t: string) => `Sèche-linge ${lbl} réservé automatiquement : ${t}`,
  confirmBooking: "Confirmer la réservation",
  slotConfirmed:  "Réservation confirmée",
  slotUpdated:    "Réservation mise à jour",
  slotDeleted:    "Réservation supprimée",
  wantModify:     "Veux-tu modifier cette réservation ?",
  bookedBy:       (r: string) => `Réservé par la chambre ${r}`,
  machineMgmt:    "Gestion des machines",
  reportOos:      "Signaler une panne",
  restore:        "Rétablir",
  oosDesc:        "Signale une machine qui ne marche pas : un administrateur vérifie et la met hors service.",
  reminderSent:   (r: string) => `Rappel envoyé · Chambre ${r}`,
  oosSet:         (lbl: string) => `${lbl} signalé hors service`,
  oosCleared:     (lbl: string) => `${lbl} remis en service`,
  reportAction:   "Signaler",
  alreadyOos:     "Déjà signalé",
  reportSent:     (lbl: string) => `Panne signalée pour ${lbl}. Un administrateur va vérifier.`,
  washerLabel:    "Machine à laver",
  dryerLabel:     "Sèche-linge",
  notaDesc:       "Qu'est-ce qui ne va pas ? Facultatif, mais ça aide à savoir qui appeler.",
  notaPlaceholder: "Ex. n'essore pas, fuite d'eau…",
  prevHad:        (r: string) => `La chambre ${r} avait ce créneau avant toi — a-t-elle récupéré son linge ?`,
  legendFree:     "Vert — Libre", legendFreeDesc: "Tu peux la réserver tout de suite.",
  legendInUse:    (t: string) => `Jaune — Occupé — Créneau en cours, fin à ${t}.`,
  legendPrev:     "Chambre — Créneau précédent — Indique qui avait le créneau avant toi.",
  legendOos:      "Rouge — Hors service — Tu peux quand même la réserver, à tes risques.",
  legendAuto:     "Sèche-linge automatique — en réservant une machine à laver, celui qui correspond est réservé pour le créneau suivant.",
  lgFree: "Libre", lgInUse: "Occupé", lgOos: "Hors service", lgPrev: "Créneau précédent",
  lgFreeD: "Personne n'a pris ce créneau.",
  lgInUseD: (t: string) => `Créneau en cours, fin à ${t}.`,
  lgOosD: "Panne confirmée par l'administration. Tu peux quand même la réserver, à tes risques.",
  lgPrevD: "La chambre qui avait le créneau avant toi.",
  insertRoom:     "Numéro de chambre",
  back:           "← Retour",
  backModify:     "← Modifier",
  changeRoom:     "Changer de chambre",
  loading:        "Chargement des réservations…",
  retry:          "Réessayer",
  netError:       "Impossible de joindre le serveur. Vérifie ta connexion.",
  taken:          (r?: string) => r ? `Déjà pris par la chambre ${r}` : "Déjà pris",
  genericError:   "Erreur, réessaie.",
  soloDirezione:  "Ce créneau appartient à la Direction : seul un administrateur peut le libérer.",
  navLavanderia: "Buanderie", navCinema: "Cinéma", navMusica: "Musique",
  navMacchine: "Machines", navSegnalazioni: "Signalements",
  navRicorrenti: "Récurrents", navManutenzione: "Maintenance",
  amministrazione: "Administration",
  mesiBrevi: ["janv","févr","mars","avr","mai","juin","juil","août","sept","oct","nov","déc"],
  navLingua: "Langue",
  notaFacoltativa: "Facultatif : tu peux envoyer sans rien écrire.",
  inviaSegnalazione: "Envoyer le signalement",
  impostazioni: "Réglages",
  notificheTurni: "Rappels de créneaux",
  notificheBloccate: "Bloquées par le navigateur",
  attive: "Activés",
  nonAttive: "Désactivés",
  installaApp: "Installer l'application",
  accessibilita: "Accessibilité",
  privacy: "Confidentialité", privacySub: "Comment nous traitons tes données",
  privacyDatiTitolo: "Quelles données nous collectons",
  privacyDatiBody: "Le numéro de chambre que tu saisis pour te connecter ; si tu actives les rappels, l'identifiant de ton appareil (pour les notifications push) ou de ta discussion (pour Telegram) ; le texte des signalements que tu envoies. Nous ne te demandons ni nom ni autre donnée d'identité — mais le numéro de chambre reste une donnée qui peut te relier, pour quiconque sait qui habite cette chambre.",
  privacyPercheTitolo: "Pourquoi nous les utilisons",
  privacyPercheBody: "Pour te permettre de réserver les créneaux de laverie et de salle, éviter les doubles réservations et les chevauchements, et — seulement si tu l'actives — t'envoyer un rappel juste avant le début de ton créneau.",
  privacyConservazioneTitolo: "Combien de temps nous les conservons",
  privacyConservazioneBody: "Les réservations restent visibles pour la semaine en cours et la précédente, puis sont supprimées automatiquement. Les signalements et les journaux techniques sont supprimés après 180 jours. Un abonnement aux rappels (push ou Telegram) reste actif jusqu'à ce que tu le désactives toi-même dans les Réglages, ou que tu envoies /stop au bot Telegram.",
  privacyCondivisioneTitolo: "Avec qui nous partageons les données",
  privacyCondivisioneBody: "L'application tourne sur Vercel et la base de données sur Supabase, qui les hébergent pour notre compte. Si tu actives les rappels, ton appareil ou ton compte reçoit les messages via le service push de ton navigateur (Google, Apple ou Mozilla, selon l'appareil) ou via Telegram. Nous ne vendons ni ne partageons tes données à d'autres fins.",
  privacyDirittiTitolo: "Tes droits",
  privacyDirittiBody: "Tu peux désactiver les rappels à tout moment dans les Réglages : cela supprime immédiatement l'abonnement push ou Telegram lié à ton appareil. Pour accéder, corriger ou supprimer d'autres données te concernant (par ex. un signalement envoyé), contacte les personnes qui gèrent l'application.",
  promemoriaTurni: "Rappels de créneaux",
  promemoriaDesc: "On te prévient juste avant le début de ton créneau.",
  notifichePhone: "Notifications du téléphone",
  nonDisponibili: "Indisponibles sur cet appareil",
  bloccateBrowser: "Bloquées dans les réglages du navigateur",
  disattiva: "Désactiver",
  attiva: "Activer",
  nonOra: "Plus tard",
  attivaWebApp: "Activer dans la web app",
  attivaTelegram: "Activer sur Telegram",
  telegramDesc: "Pratique sur iPhone, où les notifications sont capricieuses",
  riapri: "Rouvrir",
  collega: "Associer",
  telegramErrore: "Ça n'a pas marché. Réessaie.",
  nonSiApre: "Ça ne s'est pas ouvert ?",
  riprovaTelegram: "Réessayer d'ouvrir Telegram",
  scriviCodice: "Envoie ce code au bot : ",
  codiceUsaEGetta: "Utilisable une seule fois, expire dans 24 heures.",
  navConferenze: "Polyvalente",
  salaConferenze: "Salle Polyvalente",
  liberaOra: "Libre maintenant",
  occupataOra: "Occupée maintenant",
  liberaDalle: (h: string): string => `Libre à partir de ${h}`,
  nessunaOccupazione: "Rien de prévu.",
  lavBreve: "Lav.",
  navAccount: "Comptes",
  direzioneNome: "Direction",
  sessioneAttiva: (r: string): string => `Session ${r} active : tu réserves en tant que Direction. Pour te déconnecter, touche DIREZIONE en haut.`,
  telegramAperto: "Telegram est ouvert : touche DÉMARRER dans le bot pour être connecté.",
  usaTastiera: "Tu peux aussi taper au clavier et appuyer sur Entrée.",
  autoReservedLabel: "incluse",
  giornoDopo: "(le lendemain)",
};

export default fr;
