// lingue/fr.ts — francese.

import { WEEKLY_QUOTA } from "../modello";
import type { Testi } from "./it";

const fr: Testi = {

  greeting: (h: number) => h < 12 ? "Bonjour" : h < 18 ? "Bon après-midi" : "Bonsoir",
  fmtTime:  (d: Date) => d.toLocaleTimeString("fr-FR", { hour:"2-digit", minute:"2-digit" }),
  fmtDay:   (d: Date) => d.toLocaleDateString("fr-FR", { weekday:"long", day:"numeric", month:"long" }),
  days:     ["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"],
  room:     "Chambre", camera: "chambre",
  welcome:  "Einaudi Plus", enterRoom: "Saisis ton numéro de chambre pour continuer",
  installTitle: "Installer Einaudi Plus",
  installBody: "Ajoute-la à l'écran d'accueil : elle s'ouvre en plein écran et peut t'envoyer les rappels de créneaux.",
  installIosBody: "Pour l'installer sur iPhone : touche le bouton Partager du navigateur, puis « Sur l'écran d'accueil ».",
  installIosStep: "Partager  →  Sur l'écran d'accueil",
  installAndroidBody: "Ouvre le menu du navigateur et choisis « Ajouter à l'écran d'accueil » (ou « Installer l'application »).",
  installAndroidStep: "Menu  →  Ajouter à l'écran d'accueil",
  installCta: "Installer", installLater: "Plus tard", installIosDone: "J'ai compris",
  addFav: "Ajouter un favori", day: "Jour", timeSlot: "Créneau horaire", favAlready: "Déjà dans les favoris",
  chooseWasher: "Choisis le lave-linge", noFreeWashers: "Aucun lave-linge libre sur ce créneau.",
  feedback: "Retour", feedbackBody: "Une suggestion ou un problème ? Écris-nous.",
  feedbackPlaceholder: "Écris ton message ici…", feedbackSend: "Envoyer", feedbackSending: "Envoi en cours…",
  feedbackThanks: "Merci ! Message envoyé ✓", feedbackError: "L'envoi a échoué, réessaie.",
  skip:     "Continuer sans s'identifier",
  machines: "Lave-linge",
  washers:  "Lave-linge", dryers: "Sèche-linge", washer: "Lave-linge", dryer: "Sèche-linge",
  free:     "Libre", inUse: "Occupé", oos: "Hors service", operative: "En service",
  book:     "Réserver", reminder: "Rappel", sendReminder: "Envoyer un rappel", sent: "Envoyé ✓",
  bookAnyway:   "Réserver quand même",
  oosWarnTitle: "Machine hors service",
  oosWarnBody:  "L'administration l'a vérifiée et signalée comme en panne. Tu peux quand même la réserver, mais elle ne marchera probablement pas.",
  oosDryerWarn: (m: string) => `Le sèche-linge ${m} est hors service : tu devras peut-être étendre ton linge.`,
  oosWasherWarn:(m: string) => `Le lave-linge ${m} est hors service : il risque de ne pas démarrer.`,
  currentSlot: "Créneau en cours", prevSlot: "Créneau précédent", now: "maintenant", prev: "préc.",
  yourBookings: "Tes réservations",
  inProgressNow: "En cours",
  noActiveBookings: "Aucune réservation en cours",
  freeTodayLabel: "créneaux libres aujourd'hui",
  favorites: "Favoris",
  noFavs: "Touche la ★ à côté d'un horaire dans l'onglet Journalier pour l'ajouter aux favoris.",
  favFree: "Libre", favFull: "Complet", favPast: "Passé",
  remainingChip: (n: number) => n >= 0 ? `${n} restant${n === 1 ? "" : "s"}` : `${-n} en trop`,
  slotEndsIn: "Se termine dans",
  remainingMsg: (n: number) => n > 0
    ? `Tu peux encore réserver ${n} créneau${n === 1 ? "" : "x"} cette semaine (max ${WEEKLY_QUOTA} par chambre).`
    : n === 0
    ? `Tu as utilisé tes deux créneaux de la semaine (max ${WEEKLY_QUOTA} par chambre).`
    : `Tu as dépassé la limite de ${WEEKLY_QUOTA} créneaux par semaine (${-n} en trop).`,
  altraLavanderia: "Cette chambre dépend de l'autre buanderie. Tu ne peux réserver que les machines de ton bâtiment.",
  noQuota: "sans limite",
  howItWorks: "Comment ça marche",
  autoWash: (_end: string) => `Le sèche-linge correspondant est réservé automatiquement pour le créneau suivant.`,
  daily:    "Journalier", weekly: "Semaine", overview: "Vue d'ensemble",
  thisWeek: "Semaine en cours",
  confirm:  "Confirmer", cancel: "Annuler", modify: "Changer de chambre", delete: "Supprimer la réservation",
  forMe:    (r: string) => `Pour moi — Chambre ${r}`,
  forOther: "Pour quelqu'un d'autre",
  forDirezione: "Pour la Direction",
  whoIsIt:  "Pour qui est la réservation ?",
  chooseFree: "Choisis un lave-linge libre",
  occupied: "Occupé",
  autoReserved: (lbl: string, t: string) => `Sèche-linge ${lbl} réservé automatiquement : ${t}`,
  confirmBooking: "Confirmer la réservation",
  slotConfirmed:  "Réservation confirmée",
  slotUpdated:    "Réservation mise à jour",
  slotDeleted:    "Réservation supprimée",
  wantModify:     "Veux-tu modifier cette réservation ?",
  bookedBy:       (r: string) => `Réservé par la chambre ${r}`,
  machineMgmt:    "Gestion des machines",
  reportOos:      "Signaler une panne",
  restore:        "Rétablir",
  oosDesc:        "Signale une machine qui ne marche pas : un administrateur vérifie et la met hors service.",
  reminderSent:   (r: string) => `Rappel envoyé · Chambre ${r}`,
  oosSet:         (lbl: string) => `${lbl} signalé hors service`,
  oosCleared:     (lbl: string) => `${lbl} remis en service`,
  reportAction:   "Signaler",
  alreadyOos:     "Déjà signalé",
  reportSent:     (lbl: string) => `Panne signalée pour ${lbl}. Un administrateur va vérifier.`,
  washerLabel:    "Lave-linge",
  dryerLabel:     "Sèche-linge",
  notaDesc:       "Qu'est-ce qui ne va pas ? Facultatif, mais ça aide à savoir qui appeler.",
  notaPlaceholder: "Ex. n'essore pas, fuite d'eau…",
  booked:         (lbl: string) => `Lave-linge ${lbl} réservé !`,
  prevHad:        (r: string) => `La chambre ${r} avait ce créneau avant toi — a-t-elle récupéré son linge ?`,
  legendFree:     "Vert — Libre", legendFreeDesc: "Tu peux la réserver tout de suite.",
  legendInUse:    (t: string) => `Jaune — Occupé — Créneau en cours, fin à ${t}.`,
  legendPrev:     "Chambre — Créneau précédent — Indique qui avait le créneau avant toi.",
  legendOos:      "Rouge — Hors service — Tu peux quand même la réserver, à tes risques.",
  legendAuto:     "Sèche-linge automatique — en réservant un lave-linge, celui qui correspond est réservé pour le créneau suivant.",
  lgFree: "Libre", lgInUse: "Occupé", lgOos: "Hors service", lgPrev: "Créneau précédent",
  lgFreeD: "Tu peux la réserver tout de suite.",
  lgInUseD: (t: string) => `Créneau en cours, fin à ${t}.`,
  lgOosD: "Panne confirmée par l'administration. Tu peux quand même la réserver, à tes risques.",
  lgPrevD: "La chambre qui avait le créneau avant toi.",
  insertRoom:     "Numéro de chambre",
  back:           "← Retour",
  backModify:     "← Modifier",
  changeRoom:     "Changer de chambre",
  loading:        "Chargement des réservations…",
  retry:          "Réessayer",
  netError:       "Impossible de joindre le serveur. Vérifie ta connexion.",
  taken:          (r?: string) => r ? `Déjà pris par la chambre ${r}` : "Déjà pris",
  genericError:   "Erreur, réessaie.",
  soloDirezione:  "Ce créneau appartient à la Direction : seul un administrateur peut le libérer.",
  navLavanderia: "Buanderie", navCinema: "Cinéma", navMusica: "Musique",
  navMacchine: "Machines", navSegnalazioni: "Signalements",
  navRicorrenti: "Récurrents", navManutenzione: "Maintenance",
  amministrazione: "Administration",
  mesiBrevi: ["janv","févr","mars","avr","mai","juin","juil","août","sept","oct","nov","déc"],
  navLingua: "Langue",
  notaFacoltativa: "Facultatif : tu peux envoyer sans rien écrire.",
  inviaSegnalazione: "Envoyer le signalement",
  impostazioni: "Réglages",
  notificheTurni: "Rappels de créneaux",
  notificheBloccate: "Bloquées par le navigateur",
  attive: "Activés",
  nonAttive: "Désactivés",
  installaApp: "Installer l'application",
  accessibilita: "Accessibilité",
  promemoriaTurni: "Rappels de créneaux",
  promemoriaDesc: "On te prévient juste avant le début de ton créneau.",
  notifichePhone: "Notifications du téléphone",
  nonDisponibili: "Indisponibles sur cet appareil",
  bloccateBrowser: "Bloquées dans les réglages du navigateur",
  disattiva: "Désactiver",
  attiva: "Activer",
  telegramDesc: "Pratique sur iPhone, où les notifications sont capricieuses",
  riapri: "Rouvrir",
  collega: "Associer",
  telegramErrore: "Ça n'a pas marché. Réessaie.",
  nonSiApre: "Ça ne s'est pas ouvert ?",
  riprovaTelegram: "Réessayer d'ouvrir Telegram",
  scriviCodice: "Envoie ce code au bot : ",
  codiceUsaEGetta: "Utilisable une seule fois, expire dans 24 heures.",
};

export default fr;
