// lingue/it.ts — italiano, la lingua di riferimento.
//
// Da questo file TypeScript ricava il tipo `Testi`: tutte le altre lingue
// devono avere ESATTAMENTE queste chiavi, altrimenti la build si ferma. È il
// motivo per cui una traduzione dimenticata non può arrivare in produzione.
//
// Per aggiungere una lingua: si copia questo file, si traduce, e si aggiunge
// una riga in i18n.ts. Niente altro.

import { WEEKLY_QUOTA } from "../modello";

const it = {

  greeting: (h: number): string => h < 12 ? "Buongiorno" : h < 17 ? "Buon pomeriggio" : "Buonasera",
  fmtTime:  (d: Date): string => d.toLocaleTimeString("it-IT", { hour:"2-digit", minute:"2-digit" }),
  fmtDay:   (d: Date): string => d.toLocaleDateString("it-IT", { weekday:"long", day:"numeric", month:"long" }),
  days:     ["Lun","Mar","Mer","Gio","Ven","Sab","Dom"],
  room:     "Camera", camera: "camera",
  welcome:  "Einaudi Plus", enterRoom: "Inserisci il numero della tua stanza per accedere",
  installTitle: "Installa Einaudi Plus",
  installBody: "Aggiungila alla schermata Home: si apre come un'app a tutto schermo e può inviarti i promemoria dei turni.",
  installIosBody: "Per installarla su iPhone: tocca il tasto Condividi del browser, poi scegli «Aggiungi a Home».",
  installIosStep: "Condividi  →  Aggiungi a Home",
  installAndroidBody: "Apri il menu del browser e scegli «Aggiungi pagina a → Schermata Home» (o «Installa app»).",
  installAndroidStep: "Menu  →  Aggiungi a Schermata Home",
  installCta: "Installa", installLater: "Più tardi", installIosDone: "Ho capito",
  favsIntro: "I turni che rivuoi ogni settimana.",
  addFav: "Aggiungi preferito",
  removeFav: "Togli dai preferiti", day: "Giorno", timeSlot: "Fascia oraria", favAlready: "Già nei preferiti",
  chooseWasher: "Scegli la lavatrice", noFreeWashers: "Nessuna lavatrice libera in questo turno.",
  feedback: "Feedback", feedbackBody: "Hai suggerimenti o hai trovato un problema? Scrivici.",
  feedbackPlaceholder: "Scrivi qui il tuo messaggio…", feedbackSend: "Invia", feedbackSending: "Invio feedback…",
  feedbackThanks: "Grazie! Feedback inviato ✓", feedbackError: "Invio non riuscito, riprova.",
  skip:     "Continua senza accedere",
  machines: "Lavatrici",
  washers:  "Lavatrici", dryers: "Asciugatrici", washer: "Lavatrice", dryer: "Asciugatrice",
  free:     "Libera", inUse: "In uso", oos: "Fuori servizio", operative: "Operativa",
  book:     "Prenota", reminder: "Reminder", sendReminder: "Manda reminder", sent: "Inviato ✓",
  bookAnyway:   "Prenota comunque",
  // Attenzione al significato: `is_oos` viene messo dall'amministratore DOPO
  // aver verificato una segnalazione, non dal residente che segnala. Quindi
  // qui il guasto è confermato, non in attesa di conferma.
  oosWarnTitle: "Macchina fuori servizio",
  oosWarnBody:  "L'amministrazione l'ha verificata e segnata come guasta. Puoi prenotarla lo stesso, ma è probabile che non funzioni.",
  oosDryerWarn: (m: string): string => `L'asciugatrice ${m} è fuori servizio: potresti dover stendere il bucato.`,
  oosWasherWarn:(m: string): string => `La lavatrice ${m} è fuori servizio: potrebbe non partire.`,
  currentSlot: "Turno corrente", prevSlot: "Turno precedente", now: "ora", prev: "prec.",
  yourBookings: "Le tue prenotazioni",
  // Le due chiamate all'azione sotto il turno corrente. Dicono "prenota"
  // perche' e' la parola che si cerca, e nominano il QUANDO perche' e' la
  // cosa che si sceglie: il vecchio "+ Prenota" accanto alla macchina non
  // diceva ne' l'uno ne' l'altro.
  bookToday:     "Prenota per oggi",
  bookTodayHint: "Scegli l'orario fra quelli liberi di oggi",
  bookOtherDay:     "Prenota per un altro giorno",
  bookOtherDayHint: "Guarda tutta la settimana e scegli",
  backToDashboard:  "Torna alla dashboard",
  navStrutture: "Menu",
  bookTitle: "Prenota",
  feedbackApp: "Feedback sull'app",
  machinesInfo: "Chi ha le macchine in questo turno, e chi le aveva prima.",
  inProgressNow: "In corso ora",
  noActiveBookings: "Nessuna prenotazione attiva",
  freeTodayLabel: "turni liberi oggi",
  favorites: "Preferiti",
  noFavs: "Tocca la ★ accanto a un orario nella scheda Giornaliero per aggiungerlo ai preferiti.",
  // Sulla riga di un preferito ancora libero: dice che NON e' una
  // prenotazione, che era la confusione da togliere.
  bookSlot: "Prenota un turno",
  bookAnother: "Prenota un altro turno",
  favAvailable: "Il tuo turno preferito è libero",
  favFree: "Libero", favFull: "Pieno", favPast: "Passato",
  remainingChip: (n: number): string => n >= 0 ? `${n} rimanent${n === 1 ? "e" : "i"}` : `${-n} in più`,
  // "18:15" da solo non diceva se fosse l'inizio o la fine: la torta
  // accanto misura la fine, quindi questo deve dire l'inizio, a parole.
  slotFrom: (ora: string): string => `Turno delle ${ora}`,
  slotEndsIn: "Termina tra",
  remainingMsg: (n: number): string => n > 0
    ? `Puoi ancora prenotare ${n} ${n === 1 ? "turno" : "turni"} questa settimana (max ${WEEKLY_QUOTA} a camera).`
    : n === 0
    ? `Hai usato entrambi i turni di questa settimana (max ${WEEKLY_QUOTA} a camera).`
    : `Hai superato il limite settimanale di ${WEEKLY_QUOTA} turni (${-n} in più).`,
  altraLavanderia: "Quella camera è dell'altra lavanderia. Puoi prenotare solo le macchine del tuo edificio.",
  noQuota: "senza limite",
  howItWorks: "Come funziona",
  autoWash: (_end: string): string => `Lavatrice corrispondente prenotata automaticamente per il turno successivo.`,
  daily:    "Giornaliero", weekly: "Settimana", overview: "Panoramica",
  thisWeek: "Settimana corrente",
  confirm:  "Conferma", cancel: "Annulla", modify: "Modifica stanza", delete: "Elimina prenotazione",
  forMe:    (r: string): string => `Per me — Camera ${r}`,
  forOther: "Per qualcun altro",
  forDirezione: "Per la Direzione",
  whoIsIt:  "Per chi è la prenotazione?",
  chooseFree: "Scegli una lavatrice libera",
  occupied: "Occupata",
  autoReserved: (lbl: string, t: string): string => `Asciugatrice ${lbl} auto-riservata: ${t}`,
  confirmBooking: "Conferma prenotazione",
  slotConfirmed:  "Prenotazione confermata",
  slotUpdated:    "Prenotazione aggiornata",
  slotDeleted:    "Prenotazione eliminata",
  wantModify:     "Vuoi modificare questa prenotazione?",
  bookedBy:       (r: string): string => `Prenotata dalla stanza ${r}`,
  machineMgmt:    "Gestione macchine",
  reportOos:      "Segnala un guasto",
  restore:        "Ripristina",
  oosDesc:        "Segnala una macchina che non funziona: un amministratore verifica e la mette fuori servizio.",
  reminderSent:   (r: string): string => `Reminder inviato · Stanza ${r}`,
  oosSet:         (lbl: string): string => `${lbl} segnalata fuori servizio`,
  oosCleared:     (lbl: string): string => `${lbl} ripristinata`,
  reportAction:   "Segnala",
  alreadyOos:     "Già segnalata",
  reportSent:     (lbl: string): string => `Guasto segnalato per ${lbl}. Un amministratore verificherà.`,
  washerLabel:    "Lavatrice",
  dryerLabel:     "Asciugatrice",
  notaDesc:       "Cosa non va? Facoltativo, ma aiuta a capire chi chiamare.",
  notaPlaceholder: "Es. non centrifuga, perde acqua…",
  prevHad:        (r: string): string => `La stanza ${r} aveva questo turno prima di te — ha già ritirato il bucato?`,
  legendFree:     "Verde — Libera", legendFreeDesc: "Puoi prenotarla subito.",
  legendInUse:    (t: string): string => `Giallo — In uso — Turno in corso, fine alle ${t}.`,
  legendPrev:     "Camera — Turno precedente — Indica chi aveva lo slot prima di te.",
  legendOos:      "Rosso — Fuori servizio — Puoi prenotarla comunque, a tuo rischio.",
  legendAuto:     "Asciugatrice automatica — prenotando una lavatrice, quella corrispondente viene riservata per il turno successivo.",
  lgFree: "Libera", lgInUse: "In uso", lgOos: "Fuori servizio", lgPrev: "Turno precedente",
  lgFreeD: "Nessuno l'ha presa per questo turno.",
  lgInUseD: (t: string): string => `Turno in corso, fine alle ${t}.`,
  lgOosD: "Guasto confermato dall'amministrazione. Puoi prenotarla comunque, a tuo rischio.",
  lgPrevD: "La camera che aveva lo slot prima di te.",
  insertRoom:     "Numero di stanza",
  back:           "← Indietro",
  backModify:     "← Modifica",
  changeRoom:     "Cambia camera",
  loading:        "Carico le prenotazioni…",
  retry:          "Riprova",
  netError:       "Impossibile contattare il server. Controlla la connessione.",
  taken:          (r?: string): string => r ? `Già occupata dalla stanza ${r}` : "Già occupata",
  genericError:   "Errore, riprova.",
  soloDirezione:  "Questo turno è della Direzione: può toglierlo solo un amministratore.",
  // Voci di navigazione
  navLavanderia: "Lavanderia", navCinema: "Cinema", navMusica: "Musica",
  navMacchine: "Macchine", navSegnalazioni: "Segnalazioni",
  navRicorrenti: "Ricorrenti", navManutenzione: "Manutenzione",
  amministrazione: "Amministrazione",
  mesiBrevi: ["gen","feb","mar","apr","mag","giu","lug","ago","set","ott","nov","dic"],
  navLingua: "Lingua",
  notaFacoltativa: "Facoltativo: puoi inviare anche senza scrivere niente.",
  inviaSegnalazione: "Invia la segnalazione",
  impostazioni: "Impostazioni",
  notificheTurni: "Notifiche turni",
  notificheBloccate: "Bloccate dal browser",
  attive: "Attive",
  nonAttive: "Non attive",
  installaApp: "Installa l'app",
  accessibilita: "Accessibilità",
  privacy: "Privacy", privacySub: "Come trattiamo i tuoi dati",
  privacyDatiTitolo: "Che dati raccogliamo",
  privacyDatiBody: "Il numero di camera che inserisci per accedere; se attivi i promemoria, l'identificativo del dispositivo (per le notifiche push) o della chat (per Telegram); il testo delle segnalazioni che invii. Non ti chiediamo nome, cognome o altri dati anagrafici: il numero di camera resta comunque un dato che il Collegio può ricondurre a te tramite il registro alloggi.",
  privacyPercheTitolo: "Perché li usiamo",
  privacyPercheBody: "Per farti prenotare i turni di lavanderia e le sale, evitare doppie prenotazioni e sovrapposizioni, e — solo se lo attivi tu — inviarti un promemoria poco prima del tuo turno.",
  privacyConservazioneTitolo: "Per quanto tempo li conserviamo",
  privacyConservazioneBody: "Le prenotazioni restano visibili per la settimana corrente e la precedente, poi vengono cancellate automaticamente. Le segnalazioni e i registri tecnici vengono cancellati dopo 180 giorni. L'iscrizione ai promemoria (push o Telegram) resta finché non la disattivi tu stesso dalle Impostazioni, o scrivendo /stop al bot Telegram.",
  privacyCondivisioneTitolo: "Con chi condividiamo i dati",
  privacyCondivisioneBody: "L'app gira su Vercel e il database su Supabase, che li ospitano per nostro conto. Se attivi i promemoria, il tuo dispositivo o account riceve i messaggi tramite il servizio push del tuo browser (Google, Apple o Mozilla, a seconda del dispositivo) o tramite Telegram. Non vendiamo né condividiamo i tuoi dati per altri scopi.",
  privacyDirittiTitolo: "I tuoi diritti",
  privacyDirittiBody: "Puoi disattivare i promemoria in qualsiasi momento dalle Impostazioni: cancella subito l'iscrizione push o Telegram collegata al tuo dispositivo. Per accedere, correggere o cancellare gli altri dati che ti riguardano (es. una segnalazione inviata), contatta l'amministrazione del Collegio.",
  promemoriaTurni: "Promemoria turni",
  promemoriaDesc: "Ti avvisiamo poco prima che inizi il tuo turno.",
  notifichePhone: "Notifiche del telefono",
  nonDisponibili: "Non disponibili su questo dispositivo",
  bloccateBrowser: "Bloccate nelle impostazioni del browser",
  disattiva: "Disattiva",
  attiva: "Attiva",
  nonOra: "Non ora",
  telegramDesc: "Utile su iPhone, dove le notifiche sono capricciose",
  riapri: "Riapri",
  collega: "Collega",
  telegramErrore: "Non è riuscito. Riprova.",
  nonSiApre: "Non si è aperto?",
  riprovaTelegram: "Riprova ad aprire Telegram",
  scriviCodice: "Scrivi al bot questo codice: ",
  codiceUsaEGetta: "Vale una volta sola e scade in 24 ore.",
  navConferenze: "Polivalente",
  salaConferenze: "Sala Polivalente",
  liberaOra: "Libera adesso",
  occupataOra: "Occupata adesso",
  liberaDalle: (h: string): string => `Si libera alle ${h}`,
  nessunaOccupazione: "Nessuna occupazione in programma.",
  lavBreve: "Lav.",
  navAccount: "Account",
  direzioneNome: "Direzione",
  sessioneAttiva: (r: string): string => `Sessione ${r} attiva: prenoti come Direzione. Per uscire tocca DIREZIONE in alto.`,
  telegramAperto: "Ho aperto Telegram: tocca AVVIA nel bot e sei collegato.",
  usaTastiera: "Puoi anche digitare da tastiera e premere Invio.",
  autoReservedLabel: "inclusa",
  giornoDopo: "(del giorno successivo)",
};

export default it;

/** La forma che ogni lingua deve avere. Deriva dall'italiano. */
export type Testi = typeof it;
